#! /bin/sh
# ~/.config/bspwm/bspwmrc

pgrep -x sxhkd > /dev/null || sxhkd &

#test comment
$HOME/.config/polybar/launch.sh

bspc monitor DP-1 -d 1 2 3
bspc monitor DP-4 -d 4 5 6 7
bspc monitor HDMI-0 -d 8 9 10

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

nitrogen --restore &
picom --blur-method dual_kawase --blur-strength 5 --backend glx