#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config normal_border_color "#103c48"
bspc config focused_border_color "#cb4b16"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true 

#Autostart
sxhkd &
dunst &
polybar &
feh --bg-center ~/dotfiles/wallpapers/1.jpg &
